### PR TITLE
Update persons.json

### PR DESCRIPTION
**Pull request by sami-alajrami**
adding my name to the list.

### CODE REVIEW

**Comment by kryptag** [comment]
@lakruzz

**Review by lakruzz — APPROVED** [review]

**Comment by lakruzz** [comment]
@sami-alajrami @kryptag 

I can't work out why Github insists that there is a merge conflict here - and I can't work the process they recommend - since I don't have write access to @sami-alajrami's clone.

@sami-alajrami in general, there is no need for creating a fork, just for applying a change in a repo, that belongs to an orgainsation, of which you are already a member - you can just simply create a new branch - within the same repo.

**Comment by sami-alajrami** [comment]
Thanks @lakruzz for sorting it out.

**Comment by lakruzz** [comment]
@sami-alajrami, @kryptag closed with Praqma/mailsignature#5

**Pull request closed without merging**
